{{- if .Values.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "chart.fullname" . }}-metrics
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.prometheus.metricsPort }}
    {{- if .Values.prometheus.networkPolicyIngress }}
    from: {{ .Values.prometheus.networkPolicyIngress | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
