apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "chart.fullname" . }}-smtp
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          "kube-mail.helmich.me/smtp-access": "true"
    ports:
    - protocol: TCP
      port: {{ .Values.smtp.service.internalPort }}
