{{- if .Values.rbac.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "chart.fullname" . }}-policies
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ["kube-mail.helmich.me"]
  resources: ["emailpolicies", "smtpservers"]
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "chart.fullname" . }}-podwatcher
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  - get
  - list
  - watch


---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "chart.fullname" . }}-podwatcher
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "chart.fullname" . }}-podwatcher
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "chart.fullname" . }}-policies
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "chart.fullname" . }}-policies
  apiGroup: rbac.authorization.k8s.io
{{- end }}
