apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  {{- with (include "chart.commonLabels" .) }}
  labels: {{ . | nindent 4 }}
  {{- end }}
  {{- with (include "chart.commonAnnotations" .) }}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.smtp.service.externalPort }}
      targetPort: {{ .Values.smtp.service.internalPort }}
      protocol: TCP
      name: smtp
    - port: {{ .Values.prometheus.metricsPort }}
      targetPort: {{ .Values.prometheus.metricsPort }}
      protocol: TCP
      name: metrics
  selector: {{- include "chart.selectorLabels" . | nindent 4 }}
