{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- if .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- .Values.prometheus.serviceMonitor.additionalLabels | toYaml | nindent 4}}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
{{- end }}