{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{ include "chart.metaLabels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       {{ template "chart.fullname" . }}
  updatePolicy:
    updateMode: Auto
  resourcePolicies:
    containerPolicies:
      - containerName: kube-mail
        maxAllowed: {{ .Values.verticalPodAutoscaler.maxAllowed | toYaml | nindent 10 }}
        minAllowed: {{ .Values.verticalPodAutoscaler.minAllowed | toYaml | nindent 10 }}
{{- end }}