policy:
  provider: kubernetes
  kubernetes:
    inCluster:
      __name: KUBEMAIL_KUBERNETES_INCLUSTER
      __format: json
    static: KUBEMAIL_KUBERNETES_POLICY

rateLimiter:
  redis:
    host: KUBEMAIL_REDIS_HOST
    port: KUBEMAIL_REDIS_PORT
    password: KUBEMAIL_REDIS_PASSWORD
    sentinel:
      host: KUBEMAIL_REDIS_SENTINEL_HOST
      port: KUBEMAIL_REDIS_SENTINEL_PORT
      masterSet: KUBEMAIL_REDIS_SENTINEL_MASTERSET
watcher:
  emailPolicyInformer:
    selector:
      __name: WATCHER_EMAILPOLICYINFORMER_SELECTOR
      __format: json
  podInformer:
    selector:
      __name: WATCHER_PODINFORMER_SELECTOR
      __format: json
