policy:
  provider: kubernetes
  kubernetes:
    inCluster: false
    config: /Users/mhelmich/.kube/config
    static: ~

rateLimiter:
  redis:
    host: localhost
    port: 6379
    password: ~
    sentinel: ~
      # host: ~
      # port: ~
      # masterSet: ~

watcher:
  emailPolicyInformer:
    #selector: {"foo":"bar","bar":"foo"}
  podInformer:
    #selector: {"foo":"bar","bar":"foo"}
