apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "smtpservers.kube-mail.helmich.me"
spec:
  group: "kube-mail.helmich.me"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "smtpservers"
    singular: "smtpserver"
    kind: "SMTPServer"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["server"]
          properties:
            server:
              type: string
            port:
              type: number
              minimum: 1
            tls:
              type: boolean
            authType:
              type: string
              enum: ["PLAIN", "LOGIN", "CRAM-MD5", "SCRAM-SHA-1"]
