name: Compile & Test
on:
  push:
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    container: node:12-jessie
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run compile

  test:
    runs-on: ubuntu-latest
    container: node:12-jessie
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run test
