name: Compile & Test
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run compile

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run test

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run generate
      - name: assert no files are modified
        run: |
          git diff | cat
          git status --porcelain=v1
          test $(git status --porcelain=v1 | wc -l) -eq 0
